BASE_PROMPT = '''
Generate a fun math word problem for a child in grade 3 to 6. Theme: {topic}. Use simple language.
Format:
Question: ...
Options:
A) ...
B) ...
C) ...
D) ...
Correct Answer: ...
Explanation: ...
'''